title: BitcoinEverywhere.tech
author: MarketsByLili and Richard Myers
email: info@bitcoineverywhere.tech
description: > # this means to ignore newlines until "baseurl:"
  Bitcoin Everywhere: Technology for the rest of the world
# social links
twitter_username: MarketsByLili
github_username:  MarketsByLilis

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
